services:
  - type: web
    name: my-pissa-backend
    runtime: node
    rootDir: BackEnd
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 10000
      - key: MONGO_DB
        sync: false